### ISSUE TITLE
In windows while running hem server or watch getting error that resource //public not found for static mapping

### ISSUE THREAD

**Issue by ravitejac** [spine/hem#96]
Hi,

While running hem server or watch getting error saying that as listed below:

$ hem server
Starting Server at http://localhost:9294
ERROR: The resource \\public not found for static mapping

$ hem watch
Building application: application
C:\Users\elancer\AppData\Roaming\npm\node_modules\hem\node_modules\fs-extra\lib\                                      mkdirs\mkdirs-sync.js:49
          throw err0
          ^

Error: UNKNOWN: unknown error, mkdir '\\public\application.css\'
    at Object.fs.mkdirSync (fs.js:885:18)
    at Object.mkdirsSync (C:\Users\elancer\AppData\Roaming\npm\node_modules\hem\                                      node_modules\fs-extra\lib\mkdirs\mkdirs-sync.js:31:9)
    at CssPackage.Package.build (C:\Users\elancer\AppData\Roaming\npm\node_modul                                      es\hem\lib\package.js:289:14)
    at Application.build (C:\Users\elancer\AppData\Roaming\npm\node_modules\hem\                                      lib\package.js:142:27)
    at Hem.buildApps (C:\Users\elancer\AppData\Roaming\npm\node_modules\hem\lib\                                      hem.js:259:26)
    at Hem.watch (C:\Users\elancer\AppData\Roaming\npm\node_modules\hem\lib\hem.                                      js:155:12)
    at Hem.exec (C:\Users\elancer\AppData\Roaming\npm\node_modules\hem\lib\hem.j                                      s:213:27)
    at Function.Hem.exec (C:\Users\elancer\AppData\Roaming\npm\node_modules\hem\                                      lib\hem.js:53:34)
    at Object.<anonymous> (C:\Users\elancer\AppData\Roaming\npm\node_modules\hem                                      \bin\hem:18:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

Can you please help out of this issue.

Thanks and Regards,
Raviteja
![screenshot](https://user-images.githubusercontent.com/5286050/39742792-d3571b52-526c-11e8-96b3-2fcc3201a9c3.png)

**Comment by zcoffin86** [comment]
I ran into the same issue with Hem on Windows. If you force your `path.sep = '/'` in `package.js` just before line 181 (in `Application.prototype.applyRootDir` function) I think you'll find this error is resolved.
